WGWebsiteBundle_homepage:
    pattern:  /
    defaults: { _controller: WGWebsiteBundle:Default:index }

WGWebsiteBundle_login:
    pattern:  /login
    defaults: { _controller: WGWebsiteBundle:Default:login }

WGWebsiteBundle_autocomplete:
    pattern:  /ajax/autocomplete
    defaults: { _controller: WGWebsiteBundle:Ajax:autocomplete }
